# Generated by Django 3.2.6 on 2021-09-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Courses', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
