# Generated by Django 3.2.6 on 2021-11-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0002_delete_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.TextField()),
                ('gender', models.BooleanField()),
                ('study', models.BooleanField()),
                ('level', models.BooleanField()),
                ('course', models.BooleanField()),
                ('DateField', models.DateField()),
                ('residence', models.TextField()),
                ('nationality', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Applications',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
