# Generated by Django 3.2.6 on 2021-11-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='DateField',
        ),
        migrations.RemoveField(
            model_name='application',
            name='file',
        ),
        migrations.RemoveField(
            model_name='application',
            name='study',
        ),
        migrations.AddField(
            model_name='application',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='application',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='application',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='application',
            name='other_contact',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='other_names',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='where',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='application',
            name='level',
            field=models.CharField(choices=[(1, 'undergraduate'), (2, 'postgraduate')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='nationality',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='residence',
            field=models.TextField(null=True),
        ),
    ]
