# Generated by Django 3.2.6 on 2021-11-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20211114_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='course',
            new_name='courses',
        ),
        migrations.AddField(
            model_name='application',
            name='campus',
            field=models.CharField(choices=[(1, 'Main campus'), (2, 'Kampala campus'), (3, 'Mbale campus'), (4, 'Arua campus'), (5, 'Kasese campus')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='studytime',
            field=models.CharField(choices=[(1, 'Regular - Main campus'), (2, 'Day - Kampala campus'), (3, 'Evening'), (4, 'Inservice - Holiday'), (5, 'Weekend')], default=None, max_length=20),
        ),
    ]
