# Generated by Django 3.2.6 on 2021-11-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_auto_20211115_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='other_names',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
