# Generated by Django 3.2.6 on 2021-11-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20211115_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='campus',
        ),
    ]
