# Generated by Django 3.2.6 on 2021-11-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_auto_20211116_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='campus',
            field=models.CharField(max_length=50),
        ),
    ]
