# Generated by Django 3.2.6 on 2021-11-18 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_alter_campus_campus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': 'Campus', 'verbose_name_plural': 'Campus'},
        ),
    ]
