# Generated by Django 3.2.6 on 2021-11-23 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_alter_campus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.campus'),
        ),
    ]
