# Generated by Django 3.2.6 on 2021-11-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_application_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='campus',
            field=models.CharField(blank=True, choices=[('main campus', 'main campus'), ('kampala campus', 'kampala campus')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
    ]
