# Generated by Django 3.2.6 on 2021-11-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_auto_20211124_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='studytime',
            new_name='study',
        ),
        migrations.AlterField(
            model_name='application',
            name='campus',
            field=models.CharField(blank=True, choices=[(1, 'Main campus'), (2, 'Kampala campus'), (3, 'Mbale campus'), (4, 'Arua campus'), (5, 'Kasese campus')], max_length=30, null=True),
        ),
    ]
