# Generated by Django 3.2.6 on 2021-11-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0013_auto_20211124_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='study',
            field=models.CharField(blank=True, choices=[(1, 'Regular - Main campus'), (2, 'Day - Kampala campus'), (3, 'Evening'), (4, 'Inservice - Holiday'), (5, 'Weekend')], max_length=20, null=True),
        ),
    ]
