# Generated by Django 3.2.6 on 2021-11-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0014_alter_application_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(blank=True, choices=[(1, 'Male'), (2, 'Female')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='level',
            field=models.CharField(blank=True, choices=[(1, 'undergraduate'), (2, 'postgraduate')], max_length=20, null=True),
        ),
    ]
