# Generated by Django 3.2.6 on 2021-11-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0015_auto_20211124_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='courses',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
