# Generated by Django 3.2.6 on 2021-11-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_auto_20211130_1335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
