# Generated by Django 3.2.6 on 2021-11-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0018_rename_courses_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
